# Generated by Django 5.1.3 on 2024-11-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='university',
        ),
        migrations.AddField(
            model_name='specialty',
            name='universities',
            field=models.ManyToManyField(related_name='specialties', to='main.university'),
        ),
    ]
